"""VibeCoding generator — text (DeepSeek) + image (Replicate/OpenAI/HF/mock).

F2 feature. Produces a generated blog post about "vibe coding" for a given topic:
the text comes from the existing DeepSeek (OpenAI-compatible) client via the AI
provider registry, and a unique tile image is generated by a configurable image
provider. In ``app.dry_run`` mode (the default) both are replaced by mock
implementations so the whole pipeline runs offline without API keys.

Adapts TO the real project structure: image generation is done via httpx REST
(no ``replicate`` / ``openai`` SDKs installed), mirroring how the rest of the app
calls external services.
"""

from __future__ import annotations

import base64
import time
from pathlib import Path
from typing import Optional

import httpx

from core.config import Config
from core.database import Database
from core.exceptions import VibeCodingError
from .ai.registry import build_provider


# ---------------------------------------------------------------------------
# Image generation
# ---------------------------------------------------------------------------


class ImageGenerator:
    """Generate a tile image for a VibeCoding post.

    ``provider`` picks the backend (``replicate`` | ``openai`` | ``huggingface``
    | ``mock``). The mock path (also forced under ``app.dry_run``) renders a
    deterministic Pillow placeholder so no network/key is needed in dev.
    """

    def __init__(self, config: Config, secrets=None) -> None:
        self.config = config
        self.igc = config.vibecoding.image_generation
        from core.config import get_secrets

        self.secrets = secrets or get_secrets()

    @property
    def _real_provider(self) -> str:
        return (self.igc.provider or "mock").lower()

    async def generate(self, prompt: str) -> str:
        """Generate an image for ``prompt``; return the local file path."""
        provider = self._real_provider
        use_mock = self.config.app.dry_run or provider == "mock"
        if use_mock:
            return self._mock_image(prompt)

        if provider == "replicate":
            return await self._replicate(prompt)
        if provider == "openai":
            return await self._openai(prompt)
        if provider == "huggingface":
            return await self._huggingface(prompt)
        raise VibeCodingError(f"Unknown image provider: {provider!r}")

    # -- mock -------------------------------------------------------------
    def _mock_image(self, prompt: str) -> str:
        from PIL import Image, ImageDraw

        w = max(1, int(self.igc.width or 1024))
        h = max(1, int(self.igc.height or 1024))
        # deterministic gradient tinted by the prompt length so it looks "unique"
        seed = sum(prompt.encode("utf-8")) % 256
        img = Image.new("RGB", (w, h), (10 + seed % 20, 20 + seed % 40, 60 + seed % 120))
        draw = ImageDraw.Draw(img)
        # draw some "code lines"
        for i in range(0, h, max(4, h // 40)):
            draw.line([(0, i), (w, i)], fill=(40, 80, 180), width=2)
        path = Path(self._tmp_dir()) / f"vibe_{int(time.time())}.png"
        path.parent.mkdir(parents=True, exist_ok=True)
        img.save(path, format="PNG")
        return str(path)

    def _auth_headers(self, token: str) -> dict:
        return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    def _dims(self) -> tuple:
        return int(self.igc.width or 1024), int(self.igc.height or 1024)

    # -- replicate --------------------------------------------------------
    async def _replicate(self, prompt: str) -> str:
        token = self.secrets.replicate_api_token or self._env_key()
        if not token:
            raise VibeCodingError("Replicate token missing (set REPLICATE_API_TOKEN)")
        w, h = self._dims()
        payload = {
            "input": {
                "prompt": prompt,
                "width": w,
                "height": h,
                "num_outputs": int(self.igc.num_outputs or 1),
            }
        }
        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(
                f"https://api.replicate.com/v1/models/{self.igc.model}/predictions",
                headers=self._auth_headers(token),
                json=payload,
            )
            if resp.status_code >= 400:
                raise VibeCodingError(f"Replicate create failed ({resp.status_code}): {resp.text[:300]}")
            url = self._poll_replicate(client, self._auth_headers(token), resp.json()["urls"]["get"])
        return await self._download(url, "png")

    async def _poll_replicate(self, client, headers, get_url: str, timeout: int = 120) -> str:
        import asyncio

        for _ in range(timeout):
            r = await client.get(get_url, headers=headers)
            data = r.json()
            status = data.get("status")
            if status == "succeeded":
                output = data.get("output")
                if isinstance(output, list):
                    output = output[0] if output else None
                if not output:
                    raise VibeCodingError("Replicate returned no output image")
                return output
            if status in ("failed", "canceled"):
                raise VibeCodingError(f"Replicate generation failed: {data.get('error')}")
            await asyncio.sleep(2)
        raise VibeCodingError("Replicate generation timed out")

    # -- openai (DALL-E) --------------------------------------------------
    async def _openai(self, prompt: str) -> str:
        token = self.secrets.openai_api_key or self._env_key()
        if not token:
            raise VibeCodingError("OpenAI key missing (set OPENAI_API_KEY)")
        w, h = self._dims()
        payload = {
            "model": self.igc.model or "dall-e-3",
            "prompt": prompt,
            "n": int(self.igc.num_outputs or 1),
            "size": f"{w}x{h}",
        }
        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post("https://api.openai.com/v1/images/generations",
                                     headers=self._auth_headers(token), json=payload)
            if resp.status_code >= 400:
                raise VibeCodingError(f"OpenAI image failed ({resp.status_code}): {resp.text[:300]}")
            item = (resp.json().get("data") or [{}])[0]
            if item.get("b64_json"):
                return self._write_bytes(base64.b64decode(item["b64_json"]), "png")
            url = item.get("url")
            if not url:
                raise VibeCodingError("OpenAI returned no image")
            return await self._download(url, "png")

    # -- huggingface ------------------------------------------------------
    async def _huggingface(self, prompt: str) -> str:
        token = self.secrets.huggingface_api_key or self._env_key()
        if not token:
            raise VibeCodingError("HuggingFace token missing (set HUGGINGFACE_API_KEY)")
        w, h = self._dims()
        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(
                f"https://router.huggingface.co/hf-inference/models/{self.igc.model}",
                headers=self._auth_headers(token),
                json={"inputs": prompt, "parameters": {"width": w, "height": h}},
            )
            if resp.status_code >= 400:
                raise VibeCodingError(f"HuggingFace image failed ({resp.status_code}): {resp.text[:300]}")
            return self._write_bytes(resp.content, "png")

    # -- helpers ----------------------------------------------------------
    def _env_key(self) -> str:
        import os

        env = os.environ.get(self.igc.api_key_env, "")
        # map explicit env-var name to the Secrets field as a fallback
        mapping = {
            "REPLICATE_API_TOKEN": self.secrets.replicate_api_token,
            "OPENAI_API_KEY": self.secrets.openai_api_key,
            "HUGGINGFACE_API_KEY": self.secrets.huggingface_api_key,
        }
        return env or mapping.get(self.igc.api_key_env, "")

    async def _download(self, url: str, ext: str) -> str:
        async with httpx.AsyncClient(timeout=120.0, follow_redirects=True) as client:
            resp = await client.get(url)
            if resp.status_code >= 400:
                raise VibeCodingError(f"Image download failed ({resp.status_code})")
            return self._write_bytes(resp.content, ext)

    def _write_bytes(self, data: bytes, ext: str) -> str:
        path = Path(self._tmp_dir()) / f"vibe_{int(time.time())}.{ext}"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return str(path)

    @staticmethod
    def _tmp_dir() -> str:
        import tempfile

        return str(Path(tempfile.gettempdir()) / "vibe_imgs")


# ---------------------------------------------------------------------------
# VibeCoding generator orchestration
# ---------------------------------------------------------------------------


class VibeCodingGenerator:
    """Generate + persist a VibeCoding post.

    Constructor takes ``(db, config)`` (matching the other services in this
    project) rather than bare API keys; secrets are read from ``.env``.
    """

    def __init__(self, db: Database, config: Config) -> None:
        self.db = db
        self.config = config
        self.image_gen = ImageGenerator(config)

    def _text_prompt(self, topic: str, custom_prompt: Optional[str] = None) -> str:
        template = custom_prompt or self.config.vibecoding.default_prompts.text
        try:
            return template.format(topic=topic)
        except (IndexError, KeyError):
            return template

    def _image_prompt(self, topic: str, custom_image_prompt: Optional[str] = None) -> str:
        template = custom_image_prompt or self.config.vibecoding.default_prompts.image
        try:
            return template.format(topic=topic)
        except (IndexError, KeyError):
            return template

    async def _generate_text(self, topic: str, custom_prompt: Optional[str]) -> str:
        # Reuse the existing DeepSeek client via the AI registry. In dry_run the
        # registry auto-forces the MockProvider, so no key is needed in dev.
        provider = build_provider(self.db, self.config, "deepseek")
        system = (
            "Ты — опытный технический блогер о вайбкодинге. Пишешь живо, с примерами "
            "кода и личным опытом. Не используешь маркдаун-заголовки в теле поста, "
            "только обычный текст и код-блоки."
        )
        prompt = self._text_prompt(topic, custom_prompt)
        max_tokens = int(getattr(self.config.vibecoding.text_generation, "max_tokens", 1500) or 1500)
        return await provider.generate_text(system, prompt, max_tokens=max_tokens)

    async def generate_post(
        self,
        topic: str,
        custom_prompt: Optional[str] = None,
        custom_image_prompt: Optional[str] = None,
    ) -> dict:
        """Generate text + image for a topic; return ``{title,text,image_path}``."""
        if not topic or not str(topic).strip():
            raise VibeCodingError("topic is required")

        title = str(topic).strip()
        text = await self._generate_text(topic, custom_prompt)
        image_prompt = self._image_prompt(topic, custom_image_prompt)
        image_path = await self.image_gen.generate(image_prompt)

        return {"title": title, "text": text, "image_path": image_path}

    async def save_post(self, post_data: dict):
        """Save a generated post as a ``draft``; return the row."""
        row = await self.db.add_vibecoding_post(
            title=post_data.get("title", ""),
            topic=post_data.get("title", ""),
            prompt_text=post_data.get("prompt_text", ""),
            image_prompt=post_data.get("image_prompt", ""),
        )
        return await self.db.update_vibecoding_post(
            row.id,
            generated_text=post_data.get("text", "") or post_data.get("generated_text", ""),
            image_url=post_data.get("image_path", "") or post_data.get("image_url", ""),
        )

    async def generate_and_save(
        self,
        topic: str,
        custom_prompt: Optional[str] = None,
        custom_image_prompt: Optional[str] = None,
    ) -> int:
        """Generate a post and persist it; return the post id."""
        post_data = await self.generate_post(topic, custom_prompt, custom_image_prompt)
        post_data.setdefault("prompt_text", custom_prompt or "")
        post_data.setdefault("image_prompt", custom_image_prompt or "")
        row = await self.save_post(post_data)
        return row.id
